### ISSUE TITLE
Singapore Airlines Cargo instead of just Singapore Airlines

### ISSUE THREAD

**Issue by kirtan** [flightplan-tool/flightplan#35]
<img width="279" alt="screen shot 2019-01-23 at 3 28 09 pm" src="https://user-images.githubusercontent.com/271440/51590012-94117800-1f23-11e9-8f1e-0206a1d51b61.png">

**Comment by jd20** [comment]
Please provide a date / route that reproduces this, thanks!

**Comment by kirtan** [comment]
Sure thing! SIN-LHR 01/23/2019-2020

**Comment by zubairv85** [comment]
This is a result of SQ having the same IATA code for their passenger airlines as well as their cargo airlines. When we lookup airline information, we do it based on the IATA code and since Singapore Airlines Cargo is listed after Singapore Airlines in src/data.js, the former is used instead of the latter. Lufthansa has the same issue. 

Not sure how we can resolve this except to remove the duplicate IATA codes.

**Comment by kirtan** [comment]
no worries, just a small thing!
